// <auto-generated />
namespace Authorization_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Question : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Question));
        
        string IMigrationMetadata.Id
        {
            get { return "201510051401048_Question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
