// <auto-generated />
namespace Authorization_App.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cont_chng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cont_chng));
        
        string IMigrationMetadata.Id
        {
            get { return "201512031423450_cont_chng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
