// <auto-generated />
namespace Authorization_App.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201510231348311_test_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
